name: sgs
description: A new Flutter application.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.30
version_code: 30
buildTime: 2024-09-09

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  app_links: ^6.1.4
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.5
  flutter_bloc: ^8.1.2
  equatable: ^2.0.5
  d4: ^0.4.0
  d4_interpolate: ^1.0.3
  dio: ^5.4.0
  #  dio_http_cache: ^0.2.11
  dio_cache_interceptor: ^3.5.0
  dio_cache_interceptor_hive_store: ^3.2.2
  #  dio_cache_interceptor_isar_store: ^1.0.1
  dio_cache_interceptor_file_store: ^1.2.3
  ditredi: ^2.0.0
  encrypt: ^5.0.3
  flutter_staggered_grid_view: ^0.7.0
  uuid: ^3.0.7
  hive: ^2.2.3
  hive_flutter: ^1.0.0
  bot_toast: ^4.1.3
  #  ubuntu_font_flutter: ^0.0.1
  #  charts_common: ^0.8.1
  majascan: ^0.5.0
  shared_preferences: ^2.0.17
  url_launcher: ^6.2.6
  #  sqflite: ^2.2.4+1
  #  sqflite_common_ffi: ^2.2.1+1
  #  sembast_sqflite: ^2.1.0+1
  #  sembast_web: ^2.1.0+4
  share: ^2.0.4
  #  path: ^1.6.4
  path_provider: ^2.0.12
  path_drawing: ^1.0.1
  intl: ^0.19.0
  #  rxdart: ^0.23.1
  dartx: ^1.1.0
  get_it: ^7.2.0
  responsive_builder: ^0.7.0
  #  flutter_icons: ^1.1.0
  flutter_font_icons: ^2.2.5
  file_picker: ^8.0.6
  flex_color_picker: ^3.5.0
  pretty_json: ^2.0.0
  animations: ^2.0.7
  logger: ^2.0.2+1
  qr_flutter: ^4.1.0
  #    git:
  #      url: https://github.com/theyakka/qr.flutter
  flutter_markdown: ^0.7.3
  markdown_widget: ^2.3.2+6
  html: ^0.15.4
  ftpconnect: ^2.0.5
  graphic: ^2.1.0
  image: ^4.0.15
  #  bitmap: ^0.1.2
  #  graphx: ^1.0.4
  #  velocity_x: ^1.0.0
  file: ^7.0.0 # fix 6.1.2error
  #  file_selector: ^1.0.1
  #  file_selector_windows: ^0.9.1+4
  #  file_selector_macos: ^0.9.0+4
  #  file_selector_linux: ^0.9.1
  open_file: ^3.3.2
  #    git: https://github.com/crazecoder/open_file.git
  #  universal_io: ^1.0.2
  #  bitsdojo_window: ^0.1.1+1
  universal_platform: ^1.0.0+1
  archive: ^3.3.6
  socket_io: ^1.0.1
  get: ^4.6.6
  rotated_corner_decoration: ^2.0.0
  showcaseview: ^3.0.0
  #  flutter_window_close: ^0.2.2
  data_table_2: ^2.3.12
  # json_data_explorer: ^0.1.0 #type error
  json_view: ^0.4.1
  flutter_widget_from_html_core: ^0.15.1
  expansion_tile_card: ^3.0.0
  xterm: ^4.0.0 #^2.5.0-pre
  #  pty: ^0.2.2-pre
  flutter_pty: ^0.4.0
  dartssh2: ^2.8.2
  #  dartssh:
  #    git:
  #      url: https://github.com/Yonkers/dartssh
  #  file_selector_macos:
  #    git:
  #      url: git://github.com/google/flutter-desktop-embedding.git
  #      path: plugins/file_selector/file_selector_macos
  window_size:
    git:
      url: https://github.com/google/flutter-desktop-embedding.git
      path: plugins/window_size
  #  menubar:
  #    git:
  #      url: git://github.com/google/flutter-desktop-embedding.git
  #      path: plugins/menubar
  dbio_utils:
    git:
      url: https://gitee.com/leeoluo/dbio_util.git
  #    path: /Users/leeo/Develop/github/dbio_utils

  flutter_svg: ^2.0.7
  #  jovial_svg: ^1.1.12
  window_manager: ^0.3.9
  #  window_manager:
  #    git:
  #      url: https://github.com/rustdesk-org/window_manager
  #  desktop_multi_window: ^0.2.0
  desktop_multi_window:
    git:
      url: https://github.com/rustdesk-org/rustdesk_desktop_multi_window.git
  texture_rgba_renderer: ^0.0.16
  isar: ^4.0.0-dev.14
  isar_flutter_libs: ^4.0.0-dev.14
  #  graphx: ^1.0.12
  jdenticon_dart: ^2.0.0
  multiavatar: ^0.1.5
  package_info_plus: ^8.0.0
  flutter_spinkit: ^5.2.0
  two_dimensional_scrollables: ^0.3.1
  sticky_grouped_list: ^3.1.0
  win32_registry: ^1.1.3
  #  worker_manager: ^7.0.3
  #  sliver_tools: ^0.2.12
  #  linked_scroll_controller: ^0.2.0


dev_dependencies:
  #  analyzer: ^6.3.0
  hive_generator: ^2.0.1
  #  isar_generator: ^3.1.0+1
  build_runner: ^2.4.7
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
  fonts:
    - family: Inconsolata
      fonts:
        - asset: assets/fonts/Inconsolata.otf
  #  fonts:
  #    - family: Ubuntu
  #      fonts:
  #        - asset: packages/ubuntu_font_flutter/Ubuntu-R.ttf
  #        - asset: packages/ubuntu_font_flutter/Ubuntu-RI.ttf
  #          style: italic
  #        - asset: packages/ubuntu_font_flutter/Ubuntu-B.ttf
  #          weight: 700
  #        - asset: packages/ubuntu_font_flutter/Ubuntu-BI.ttf
  #          weight: 700
  #          style: italic
  #        - asset: packages/ubuntu_font_flutter/Ubuntu-L.ttf
  #          weight: 300
  #        - asset: packages/ubuntu_font_flutter/Ubuntu-LI.ttf
  #          weight: 300
  #          style: italic
  #        - asset: packages/ubuntu_font_flutter/Ubuntu-M.ttf
  #          weight: 500
  #        - asset: packages/ubuntu_font_flutter/Ubuntu-MI.ttf
  #          weight: 500
  #          style: italic
  #    - family: Ubuntu Mono
  #      fonts:
  #        - asset: packages/ubuntu_font_flutter/UbuntuMono-R.ttf
  #        - asset: packages/ubuntu_font_flutter/UbuntuMono-RI.ttf
  #          style: italic
  #        - asset: packages/ubuntu_font_flutter/UbuntuMono-B.ttf
  #          weight: 700
  #        - asset: packages/ubuntu_font_flutter/UbuntuMono-BI.ttf
  #          weight: 700
  #          style: italic
  #    - family: Ubuntu Condensed
  #      fonts:
  #        - asset: packages/ubuntu_font_flutter/Ubuntu-C.ttf

  assets:
    - assets/theme/themes.yaml
    - assets/icon/icon_chromosome.png
    - assets/icon/icon_filter.png
    - assets/images/account_select_options.png
    - assets/images/app_icon_512.png
    - assets/images/developing.png
    - assets/images/not_found.png
    - assets/images/seq_a.png
    - assets/images/seq_c.png
    - assets/images/seq_g.png
    - assets/images/seq_t.png
    - assets/images/sgs_logo.svg
    - assets/images/layout/genome_Browser.png
    - assets/images/layout/SG_Browser1.png
    - assets/images/layout/SG_Browser2.png
    - assets/images/layout/scBrowser.png
    - assets/images/theme/
    - assets/images/color/


msix_config:
  display_name: SGS
  msix_version: 1.0.0.0
  publisher_display_name: SWU
  identity_name: com.swu.sgs
  certificate_path: C:\Users\Administrator\certs\sgs.pfx
  certificate_password: 11231123
  capabilities: internetClient
  output_path: C:\Users\Administrator\Downloads
  output_name: sgs
  app_installer: #<-- app installer configuration
    publish_folder_path: C:\Users\Administrator\Downloads\sgs
    hours_between_update_checks: 0
    automatic_background_task: true
    update_blocks_activation: true
    show_prompt: true
    force_update_from_any_version: false